In [1]:
import numpy as np

In [2]:
print (np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
data=np.zeros((2,5))

In [6]:
data=np.ones((3,3))

In [9]:
data=np.random.rand(3,3)

In [10]:
print(data)

[[0.24503397 0.10893479 0.70125588]
 [0.69239131 0.45909913 0.58517646]
 [0.46028144 0.02955079 0.98516334]]


In [11]:
data = np.array([[1, 2, 3],
              [4, 5, 6]])

In [12]:
print(f"Data: {data}\n")
print(f"Shape: {data.shape}")

Data: [[1 2 3]
 [4 5 6]]

Shape: (2, 3)


In [13]:
data = np.transpose(data)

In [14]:
print(f"Data: {data}\n")
print(f"Shape: {data.shape}")

Data: [[1 4]
 [2 5]
 [3 6]]

Shape: (3, 2)
